---
# https://taskfile.dev
version: '3'

dotenv: [".env"]

env:
  PARENT_ENV: true

includes:
  lint:
    taskfile: .taskfiles/lint.yml
    flatten: true
  license:
    taskfile: .taskfiles/license.yml
    flatten: true
  env:
    taskfile: .taskfiles/env.yml
    flatten: true
  tests:
    taskfile: .taskfiles/tests.yml
    flatten: true
  release:
    taskfile: .taskfiles/release.yml
    flatten: true
  drmcp:
    taskfile: .taskfiles/drmcp.yml
    flatten: true
  dev:
    taskfile: .taskfiles/dev.yml
    flatten: true

tasks:
  install:
    desc: "🔧 Install dependencies (all extras)"
    cmds:
      - echo "🔧 Installing dependencies (all extras)..."
      - uv sync --all-extras --dev
    silent: true

  build:
    desc: "Build distribution packages"
    cmds:
      - echo "Building distribution packages..."
      - rm -rf dist/
      - uv build
      - echo "Build complete! Distribution files in dist/"
