---
# https://taskfile.dev
version: '3'

dotenv: [".env"]

env:
  PARENT_ENV: true

vars:
  PROJECT_SRC: "./src"
  TESTS_SRC: "./tests"

includes:
  lint:
    taskfile: .taskfiles/lint.yml
    flatten: true
  license:
    taskfile: .taskfiles/license.yml
    flatten: true
  env:
    taskfile: .taskfiles/env.yml
    flatten: true
  tests:
    taskfile: .taskfiles/tests.yml
    flatten: true
  release:
    taskfile: .taskfiles/release.yml
    flatten: true
  drmcp:
    taskfile: .taskfiles/drmcp.yml
    flatten: true
  dev:
    taskfile: .taskfiles/dev.yml
    flatten: true

tasks:
  install:
    desc: "🔧 Install dependencies (all extras)"
    cmds:
      - echo "🔧 Installing dependencies (all extras)..."
      - uv sync --all-extras --dev
    silent: true

  # Use on macOS Intel (x86_64) when install fails due to lancedb (no wheel; pulled in by crewai-tools).
  install-no-crewai:
    desc: "🔧 Install dependencies (all extras except crewai, for macOS Intel)"
    cmds:
      - echo "🔧 Installing dependencies (all extras except crewai)..."
      - uv sync --dev --extra core --extra dragent --extra langgraph --extra llamaindex --extra nat --extra pydanticai --extra auth --extra drmcp
    silent: true

  build:
    desc: "Build distribution packages"
    cmds:
      - echo "Building distribution packages..."
      - rm -rf dist/
      - uv build
      - echo "Build complete! Distribution files in dist/"
