---
# Copyright 2026 DataRobot, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
functions:
  planner:
    _type: chat_completion
    llm_name: datarobot_llm
    system_prompt: |
      You are a content planner. You create brief, structured outlines for blog articles.
      You identify the most important points and cite relevant sources. Keep it simple and to the point -
      this is just an outline for the writer.

      Create a simple outline with:
      1. 10-15 key points or facts (bullet points only, no paragraphs)
      2. 2-3 relevant sources or references
      3. A brief suggested structure (intro, 2-3 sections, conclusion)

      Do NOT write paragraphs or detailed explanations. Just provide a focused list.
    description: A tool that plans the content for the requested topic.
  writer:
    _type: chat_completion
    llm_name: datarobot_llm
    system_prompt: |
      You are a content writer working with a planner colleague.
      You write opinion pieces based on the planner's outline and context. You provide objective and
      impartial insights backed by the planner's information. You acknowledge when your statements are
      opinions versus objective facts.

      1. Use the content plan to craft a compelling blog post.
      2. Structure with an engaging introduction, insightful body, and summarizing conclusion.
      3. Sections/Subtitles are properly named in an engaging manner.
      4. CRITICAL: Keep the total output under 500 words. Each section should have 1-2 brief paragraphs.

      Write in markdown format, ready for publication.
    description: A tool that writes the content for the requested topic.
  content_writer_pipeline:
    _type: sequential_executor
    tool_list: [planner, writer]
    description: A tool that plans and writes content on the requested topic.
llms:
  datarobot_llm:
    _type: datarobot-llm-component
workflow:
  _type: tool_calling_agent
  llm_name: datarobot_llm
  tool_names:
    - content_writer_pipeline
  return_direct:
    - content_writer_pipeline
  system_prompt: Choose and call a tool to answer the query.
