---
# https://taskfile.dev
version: '3'

tasks:
  run-nat:
    desc: "🔨 Running NAT agent"
    dir: ./nat
    cmds:
      - echo "🔨 Running NAT agent"
      - uv run nat start dragent_fastapi --config_file {{.WORKFLOW_FILE | default "workflow.yaml"}} --port {{.AGENT_PORT | default "8080"}}
  run-crewai:
    desc: "🔨 Running CrewAI agent via NAT"
    dir: ./crewai
    cmds:
      - echo "🔨 Running CrewAI agent via NAT"
      - uv run nat start dragent_fastapi --config_file {{.WORKFLOW_FILE | default "workflow.yaml"}} --port {{.AGENT_PORT | default "8080"}}
  run-langgraph:
    desc: "🔨 Running LangGraph agent via NAT"
    dir: ./langgraph
    cmds:
      - echo "🔨 Running LangGraph agent via NAT"
      - uv run nat start dragent_fastapi --config_file {{.WORKFLOW_FILE | default "workflow.yaml"}} --port {{.AGENT_PORT | default "8080"}}
  run-llamaindex:
    desc: "🔨 Running LlamaIndex agent via NAT"
    dir: ./llamaindex
    cmds:
      - echo "🔨 Running LlamaIndex agent via NAT"
      - uv run nat start dragent_fastapi --config_file {{.WORKFLOW_FILE | default "workflow.yaml"}} --port {{.AGENT_PORT | default "8080"}}
  run-base:
    desc: "🔨 Running base agent via NAT"
    dir: ./base
    cmds:
      - echo "🔨 Running base agent via NAT"
      - uv run nat start dragent_fastapi --config_file {{.WORKFLOW_FILE | default "workflow.yaml"}} --port {{.AGENT_PORT | default "8080"}}
