---
# https://taskfile.dev
version: '3'

dotenv: [".env"]

vars:
  PROJECT_SRC: "./dragent ./drmcp"
  TESTS_SRC: ""

includes:
  dragent:
    taskfile: dragent/Taskfile.yaml
    dir: ./dragent
  langgraph:
    taskfile: dragent/langgraph/Taskfile.yaml
    dir: ./dragent/langgraph
  crewai:
    taskfile: dragent/crewai/Taskfile.yaml
    dir: ./dragent/crewai
  llamaindex:
    taskfile: dragent/llamaindex/Taskfile.yaml
    dir: ./dragent/llamaindex
  lint:
    taskfile: ../.taskfiles/lint.yml
    flatten: true

tasks:
  install:
    desc: "🔧 Install dependencies for a specific group of functionality"
    requires:
      vars:
      - name: GROUP
        enum:
          - dragent-nat
          - dragent-langgraph
          - dragent-crewai
          - dragent-llamaindex
    cmds:
      - echo "🔧 Installing dependencies for {{.GROUP}}"
      - uv sync --group {{.GROUP}}
