---
# https://taskfile.dev
version: '3'

dotenv: [".env"]

vars:
  PROJECT_SRC: "./dragent ./drmcp"
  TESTS_SRC: ""

includes:
  dragent:
    taskfile: dragent/Taskfile.yaml
    dir: ./dragent
  lint:
    taskfile: ../.taskfiles/lint.yml
    flatten: true

tasks:
  install:
    desc: "🔧 Install dependencies for a specific group of functionality"
    requires:
      vars:
      - name: GROUP
        enum:
          - nat
          - langgraph
          - crewai
          - llamaindex
    cmds:
      - echo "🔧 Installing dependencies for {{.GROUP}}"
      - uv sync --group dragent-{{.GROUP}} --group lint
  test-dragent:
    desc: "🧪 Run tests for dragent"
    cmds:
      - echo "🧪 Running tests for dragent"
      - uv run pytest dragent_tests -vv -s
  test-drmcp:
    desc: "🧪 Run tests for drmcp"
    cmds:
      - echo "🧪 Running tests for drmcp"
      - uv run pytest drmcp_tests -vv -s
