---
# https://taskfile.dev
version: '3'

tasks:
  run-nat:
    desc: "Running LangGraph agent via NAT"
    cmds:
      - echo "Running LangGraph agent via NAT"
      - uv run nat start dragent_fastapi --config_file workflow.yaml
