---
# https://taskfile.dev
version: '3'

tasks:
  run-nat:
    desc: "Running LangGraph agent via NAT"
    cmds:
      - echo "Running LangGraph agent via NAT"
      - uv run nat start dragent_fastapi --config_file workflow.yaml
  run:
    desc: "Run LangGraph agent with a single query"
    requires:
      vars: [INPUT]
    cmds:
      - uv run nat run --config_file workflow.yaml --input "{{.INPUT}}"
